### ISSUE TITLE
have a look

### ISSUE THREAD

**Issue by martindurant** [martindurant/awkward_extras#1]
@jpivarski - here is some scratch code that you might find useful, or not. There is an outline of an ak series for pandas, which largely passes consistency tests and works with distributed, and that small code we spoke off to dump ak into zarr 2 format. It certainly is *much* faster than loading from JSON and, given the lack of full nesting support in arrow, maybe a decent option for intermediate results. Doing the same for pure arrow would be nice, but your arrow-walking code (in ak.from_arrow) is probably the best around and I didn't want to deconstruct it.

There is no need for this small code to live here, except I wanted somewhere to put it. Feel free to use, comment, or ignore if you think its not helpful.

**Comment by jpivarski** [comment]
This is great! This is a much cleaner version of the implementation I had to remove in scikit-hep/awkward-1.0#350. I just tried it out:

```python
>>> import awkward_pandas
>>> import awkward1 as ak
>>> import pandas as pd
>>> awkward_pandas.AwkwardSeries(ak.Array([[1, 2, 3], [], [4, 5]]))
AwkwardSeries( [[1, 2, 3], [], [4, 5]] )
>>> pd.DataFrame({"x": awkward_pandas.AwkwardSeries(ak.Array([[1, 2, 3], [], [4, 5]])), "y": 100})
           x    y
0  [1, 2, 3]  100
1         []  100
2     [4, 5]  100
>>> pd.DataFrame({"x": ak.Array([[1, 2, 3], [], [4, 5]]), "y": 100})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 467, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 78, in arrays_to_mgr
    index = extract_index(arrays)
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 387, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
```

It would be great if Pandas could somehow be told that an object is convertible to a series, while not directly inheriting from `pandas.core.arrays.ExtensionArray`. Maybe if they could add a `__series__` method like NumPy's `__array__` method, which would call the above. Properties like `shape` returning `(len(self),)` are too misleading for the main `ak.Array` class. I'd want to maintain this separation between an Awkward Array and an Awkward Series (as it was in Awkward 0) without requiring users to provide the explicit wrapper when filling a DataFrame with Awkward Arrays.

I'd be happy to include this code in the main Awkward package, since it is central (it would go under `_connect`). I'm targeting Dec 1 for moving all mentions of `awkward1` → `awkward` (and `awkward` → `awkward0`), so these next two weeks might not be the best time to do it.

**Comment by martindurant** [comment]
> It would be great if Pandas could somehow be told that an object is convertible to a series

pretty sure you can only do this kind of thing by explicitly giving it the dtype. How pandas decides to treat each input is ... complex. In general, I would think users would want to always use explicit dtypes with this extension and probably *all* extensions - and that includes dask functions that take a `meta` kwarg.

**Comment by jpivarski** [comment]
Wouldn't somebody try to do what I did above? At least, if it always raised an error, that would be better than accidentally converting to a `dtype="O"` array...

**Comment by martindurant** [comment]
I don't know if they would try - probably depends on our docs/examples, and helper functions to load data into dataframes.

@tomaugspurger , any insight on auto-infering the dtype from the input to DataFrame where that input is _not_ an extension array already?

**Comment by TomAugspurger** [comment]
Right, I don't believe the interface has a way to go from "arbitrary python object" to extension array at the moment.  Some kind of `__pandas_extension_array__()` interface might be in scope. We might also be able to hack up the existing registry in `pandas.core.dtypes.base.registry` to handle "foreign" objects that aren't subclasses of ExtensionArray.

FYI: I'd recommend renaming AwkwardSeries to AwkwardExtensionArray: it's not a Series since it doesn't have a `.index`.
